spring.application.name=ai-trip-planner

# Notice the ".genai." in the middle! This tells Spring to use AI Studio, not Google Cloud.
spring.ai.google.genai.api-key=${Gemini_Api_Key}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash